// <auto-generated />
using FAQsApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAQsApp.Migrations
{
    [DbContext(typeof(FAQsAppDbContext))]
    [Migration("20241209002900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FAQsApp.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "history",
                            Name = "History"
                        },
                        new
                        {
                            CategoryId = "general",
                            Name = "General"
                        });
                });

            modelBuilder.Entity("FAQsApp.Models.FAQ", b =>
                {
                    b.Property<int>("FAQId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAQId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FAQId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            FAQId = 1,
                            Answer = "Linux is a family of open-source Unix-like operating \n                               systems based on the Linux kernel, an operating system \n                               kernel first released on September 17, 1991, by Linus \n                               Torvalds. Linux is typically packaged in a Linux distribution.",
                            CategoryId = "general",
                            Question = "What is Linux?",
                            TopicId = "linux"
                        },
                        new
                        {
                            FAQId = 2,
                            Answer = "Fedora is a Linux distribution developed by the\n                               community-supported Fedora Project which is \n                               sponsored primarily by Red Hat, a subsidiary of IBM, \n                               with additional support from other companies.",
                            CategoryId = "history",
                            Question = "What is Fedora?",
                            TopicId = "fedora"
                        },
                        new
                        {
                            FAQId = 3,
                            Answer = "Ubuntu is a Linux distribution based on Debian \n                               and composed mostly of free and open-source software. \n                               Ubuntu is officially released in three editions: \n                               Desktop, Server, and Core for Internet of things devices \n                               and robots.",
                            CategoryId = "history",
                            Question = "What is Ubuntu?",
                            TopicId = "ubuntu"
                        },
                        new
                        {
                            FAQId = 4,
                            Answer = "Arch Linux is a Linux distribution for computers \n                               with x86-64 processors. Arch Linux adheres to five \n                               principles: simplicity, modernity, pragmatism, user \n                               centrality, and versatility.",
                            CategoryId = "history",
                            Question = "What is Arch Linux?",
                            TopicId = "archlinux"
                        });
                });

            modelBuilder.Entity("FAQsApp.Models.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = "linux",
                            Name = "Linux"
                        },
                        new
                        {
                            TopicId = "fedora",
                            Name = "Fedora"
                        },
                        new
                        {
                            TopicId = "ubuntu",
                            Name = "Ubuntu"
                        },
                        new
                        {
                            TopicId = "archlinux",
                            Name = "Arch Linux"
                        });
                });

            modelBuilder.Entity("FAQsApp.Models.FAQ", b =>
                {
                    b.HasOne("FAQsApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAQsApp.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
